import 'package:flutter/widgets.dart';

/// Demo copy for the catalog, in each supported locale.
///
/// `slds_components` ships strings only for the labels the components
/// themselves own — "Close", "Retry", the 404 copy. Everything else on screen
/// in a use case is *caller* text, which the library cannot translate: a
/// button's label and an accordion's title are the consuming app's words, not
/// the design system's.
///
/// That is correct for the package and wrong for the catalog. A reviewer who
/// switches to Tamil to check Noto Sans Tamil shaping mostly saw English,
/// because the demo text was hardcoded. This is that demo text, translated,
/// so the locale addon exercises the thing it claims to.
///
/// This is catalog scaffolding, not shipped API — it is deliberately not part
/// of `slds_components`. Nothing here should be reused by a consuming app;
/// host apps localize their own strings through their own delegate.
///
/// The si/ta entries are machine-drafted and unreviewed, exactly like the
/// library's own .arb files (§6 is still open on that). They are here to
/// exercise script rendering, not to be copied into a real service.
class DemoCopy {
  const DemoCopy._(this._strings);

  /// Reads the copy for the ambient locale, falling back to English for a
  /// locale the catalog has no table for.
  factory DemoCopy.of(BuildContext context) {
    final code = Localizations.localeOf(context).languageCode;
    return DemoCopy._(_tables[code] ?? _tables['en']!);
  }

  final Map<String, String> _strings;

  /// The translation for [key], or [key] itself when it has none — an
  /// untranslated key shows up as visible English rather than a crash or a
  /// blank, which is what you want while filling the table in.
  String operator [](String key) => _strings[key] ?? key;

  static const Map<String, Map<String, String>> _tables = {
    'en': _en,
    'si': _si,
    'ta': _ta,
  };
}

/// Keys are the original English copy, so a use case reads
/// `copy['Continue']` and the English table is the identity mapping. That
/// keeps call sites legible — you can see what a preview says without
/// resolving a symbolic key — and makes a missing translation obvious.
const Map<String, String> _en = {
  'Continue': 'Continue',
  'Cancel': 'Cancel',
  'Add': 'Add',
  'Download': 'Download',
  'Add Document': 'Add Document',
  'Show dialog': 'Show dialog',
  'Show bottom sheet': 'Show bottom sheet',
  'Show snack bar': 'Show snack bar',
  'Open menu': 'Open menu',
  'Apply for a fuel quota pass': 'Apply for a fuel quota pass',
  'Label': 'Label',
  'Title': 'Title',
  'Help Text': 'Help Text',
  'Help text': 'Help text',
  'Helper text': 'Helper text',
  'Hint': 'Hint',
  'Hint Text': 'Hint Text',
  'Error Text': 'Error Text',
  'Error text': 'Error text',
  'Description': 'Description',
  'Description placeholder': 'Description placeholder',
  'Enter the description text': 'Enter the description text',
  'Page Title': 'Page Title',
  'Page content': 'Page content',
  'Card content': 'Card content',
  'Sheet content goes here': 'Sheet content goes here',
  'Content': 'Content',
  'Value': 'Value',
  'Message': 'Message',
  'Title Text': 'Title Text',
  'Tooltip Title': 'Tooltip Title',
  'About this field': 'About this field',
  'Dialog Title': 'Dialog Title',
  'Basic dialog title': 'Basic dialog title',
  'Accordion Name': 'Accordion Name',
  'Collapsed by default.': 'Collapsed by default.',
  'Service Name': 'Service Name',
  'Divider': 'Divider',
  'Progress': 'Progress',
  'Step label': 'Step label',
  'Legend': 'Legend',
  'Subtitle': 'Subtitle',
  'Badge': 'Badge',
  'NEW': 'NEW',
  'Accepted': 'Accepted',
  'Success': 'Success',
  'Error': 'Error',
  'Loading': 'Loading',
  'Modal': 'Modal',
  'Icon': 'Icon',
  'Trailing': 'Trailing',
  'Input': 'Input',
  'Prefix': 'Prefix',
  'Suffix': 'Suffix',
  'Time': 'Time',
  'National Identity Card': 'National Identity Card',
  'Birth Certificate': 'Birth Certificate',
  'Driving License': 'Driving License',
  'Fuel Pass': 'Fuel Pass',
  'My Account': 'My Account',
  'Mobile Number': 'Mobile Number',
  'Email': 'Email',
  'NIC number': 'NIC number',
  'Licence number': 'Licence number',
  'Application ID': 'Application ID',
  'Submitted date': 'Submitted date',
  'Current status': 'Current status',
  'District': 'District',
  'Select district': 'Select district',
  'Shipping address': 'Shipping address',
  'Street address': 'Street address',
  'City': 'City',
  'Postal code': 'Postal code',
  'Date posted': 'Date posted',
  'Where should we deliver your order?': 'Where should we deliver your order?',
  'All fields in this group are required.':
      'All fields in this group are required.',
  'Please complete every field before continuing.':
      'Please complete every field before continuing.',
  'Enter your NIC Number correctly': 'Enter your NIC Number correctly',
  'Enter you Birth date correctly': 'Enter you Birth date correctly',
  'Enter a valid number': 'Enter a valid number',
  'File size is too big': 'File size is too big',
  'Your Birth Certificate is ready': 'Your Birth Certificate is ready',
  'Download it now or collect it from your selected office.':
      'Download it now or collect it from your selected office.',
  'No documents added yet': 'No documents added yet',
  'Your uploaded documents will appear here once added.':
      'Your uploaded documents will appear here once added.',
  'System is down for Maintenance': 'System is down for Maintenance',
  'We promise, we\'ll be right back!': 'We promise, we\'ll be right back!',
  'Pull down from the top to refresh': 'Pull down from the top to refresh',
  'Swipe to dismiss': 'Swipe to dismiss',
  'Prepare documents': 'Prepare documents',
  'Gather all required identification and supporting files':
      'Gather all required identification and supporting files',
  'Submit application': 'Submit application',
  'Upload documents through the online portal':
      'Upload documents through the online portal',
  'Verification in progress': 'Verification in progress',
  'Our team reviews your documents (2–5 business days)':
      'Our team reviews your documents (2–5 business days)',
  'Receive approval': 'Receive approval',
  'Notification sent via email and SMS': 'Notification sent via email and SMS',
  'Option One': 'Option One',
  'Option Two': 'Option Two',
  'Option Three': 'Option Three',
  'Option Four': 'Option Four',
  'Option Five': 'Option Five',
  'Item 1': 'Item 1',
  'Item 2': 'Item 2',
  'Item 3': 'Item 3',
  'All statuses': 'All statuses',
  'Recent searches': 'Recent searches',
};

const Map<String, String> _si = {
  'Continue': 'ඉදිරියට',
  'Cancel': 'අවලංගු කරන්න',
  'Add': 'එකතු කරන්න',
  'Download': 'බාගන්න',
  'Add Document': 'ලේඛනය එකතු කරන්න',
  'Show dialog': 'සංවාදය පෙන්වන්න',
  'Show bottom sheet': 'පහළ පත්‍රය පෙන්වන්න',
  'Show snack bar': 'දැනුම්දීම පෙන්වන්න',
  'Open menu': 'මෙනුව විවෘත කරන්න',
  'Apply for a fuel quota pass': 'ඉන්ධන කෝටා බලපත්‍රයට අයදුම් කරන්න',
  'Label': 'ලේබලය',
  'Title': 'මාතෘකාව',
  'Help Text': 'උදවු පෙළ',
  'Help text': 'උදවු පෙළ',
  'Helper text': 'උදවු පෙළ',
  'Hint': 'ඉඟිය',
  'Hint Text': 'ඉඟි පෙළ',
  'Error Text': 'දෝෂ පෙළ',
  'Error text': 'දෝෂ පෙළ',
  'Description': 'විස්තරය',
  'Description placeholder': 'විස්තර ස්ථානගතකය',
  'Enter the description text': 'විස්තර පෙළ ඇතුළත් කරන්න',
  'Page Title': 'පිටු මාතෘකාව',
  'Page content': 'පිටු අන්තර්ගතය',
  'Card content': 'කාඩ් අන්තර්ගතය',
  'Sheet content goes here': 'පත්‍ර අන්තර්ගතය මෙහි යයි',
  'Content': 'අන්තර්ගතය',
  'Value': 'අගය',
  'Message': 'පණිවිඩය',
  'Title Text': 'මාතෘකා පෙළ',
  'Tooltip Title': 'මෙවලම් ඉඟි මාතෘකාව',
  'About this field': 'මෙම ක්ෂේත්‍රය ගැන',
  'Dialog Title': 'සංවාද මාතෘකාව',
  'Basic dialog title': 'මූලික සංවාද මාතෘකාව',
  'Accordion Name': 'ඇකෝඩියන් නාමය',
  'Collapsed by default.': 'පෙරනිමියෙන් හකුළා ඇත.',
  'Service Name': 'සේවා නාමය',
  'Divider': 'බෙදුම්කරු',
  'Progress': 'ප්‍රගතිය',
  'Step label': 'පියවර ලේබලය',
  'Legend': 'නාමාවලිය',
  'Subtitle': 'උපමාතෘකාව',
  'Badge': 'ලාංඡනය',
  'NEW': 'නව',
  'Accepted': 'පිළිගත්තා',
  'Success': 'සාර්ථකයි',
  'Error': 'දෝෂය',
  'Loading': 'පූරණය වෙමින්',
  'Modal': 'මොඩල්',
  'Icon': 'නිරූපකය',
  'Trailing': 'පසුපස',
  'Input': 'ආදානය',
  'Prefix': 'උපසර්ගය',
  'Suffix': 'ප්‍රත්‍යය',
  'Time': 'වේලාව',
  'National Identity Card': 'ජාතික හැඳුනුම්පත',
  'Birth Certificate': 'උප්පැන්න සහතිකය',
  'Driving License': 'රියදුරු බලපත්‍රය',
  'Fuel Pass': 'ඉන්ධන බලපත්‍රය',
  'My Account': 'මගේ ගිණුම',
  'Mobile Number': 'ජංගම දුරකථන අංකය',
  'Email': 'විද්‍යුත් තැපෑල',
  'NIC number': 'ජා.හැ. අංකය',
  'Licence number': 'බලපත්‍ර අංකය',
  'Application ID': 'අයදුම්පත් හැඳුනුම',
  'Submitted date': 'ඉදිරිපත් කළ දිනය',
  'Current status': 'වත්මන් තත්ත්වය',
  'District': 'දිස්ත්‍රික්කය',
  'Select district': 'දිස්ත්‍රික්කය තෝරන්න',
  'Shipping address': 'බෙදාහැරීමේ ලිපිනය',
  'Street address': 'වීදි ලිපිනය',
  'City': 'නගරය',
  'Postal code': 'තැපැල් කේතය',
  'Date posted': 'තැපැල් කළ දිනය',
  'Where should we deliver your order?': 'ඔබේ ඇණවුම කොහෙට බෙදාහරින්නද?',
  'All fields in this group are required.':
      'මෙම කණ්ඩායමේ සියලු ක්ෂේත්‍ර අවශ්‍ය වේ.',
  'Please complete every field before continuing.':
      'ඉදිරියට යාමට පෙර සියලු ක්ෂේත්‍ර සම්පූර්ණ කරන්න.',
  'Enter your NIC Number correctly': 'ඔබේ ජා.හැ. අංකය නිවැරදිව ඇතුළත් කරන්න',
  'Enter you Birth date correctly': 'ඔබේ උපන් දිනය නිවැරදිව ඇතුළත් කරන්න',
  'Enter a valid number': 'වලංගු අංකයක් ඇතුළත් කරන්න',
  'File size is too big': 'ගොනුවේ ප්‍රමාණය ඉතා විශාලයි',
  'Your Birth Certificate is ready': 'ඔබේ උප්පැන්න සහතිකය සූදානම්',
  'Download it now or collect it from your selected office.':
      'දැන් බාගන්න හෝ ඔබ තෝරාගත් කාර්යාලයෙන් ලබාගන්න.',
  'No documents added yet': 'තවම ලේඛන එකතු කර නැත',
  'Your uploaded documents will appear here once added.':
      'ඔබ උඩුගත කරන ලේඛන එකතු කළ පසු මෙහි දිස්වේ.',
  'System is down for Maintenance': 'නඩත්තු කටයුතු සඳහා පද්ධතිය අක්‍රියයි',
  'We promise, we\'ll be right back!':
      'අපි පොරොන්දු වෙනවා, ඉක්මනින් නැවත එනවා!',
  'Pull down from the top to refresh': 'නැවුම් කිරීමට උඩ සිට පහළට අදින්න',
  'Swipe to dismiss': 'ඉවත් කිරීමට ස්වයිප් කරන්න',
  'Prepare documents': 'ලේඛන සකසන්න',
  'Gather all required identification and supporting files':
      'අවශ්‍ය සියලු හැඳුනුම් හා සහායක ගොනු එකතු කරන්න',
  'Submit application': 'අයදුම්පත ඉදිරිපත් කරන්න',
  'Upload documents through the online portal':
      'ඔන්ලයින් ද්වාරය හරහා ලේඛන උඩුගත කරන්න',
  'Verification in progress': 'සත්‍යාපනය ක්‍රියාත්මකයි',
  'Our team reviews your documents (2–5 business days)':
      'අපගේ කණ්ඩායම ඔබේ ලේඛන සමාලෝචනය කරයි (ව්‍යාපාරික දින 2–5)',
  'Receive approval': 'අනුමැතිය ලබාගන්න',
  'Notification sent via email and SMS':
      'විද්‍යුත් තැපෑල හා කෙටි පණිවිඩ මගින් දැනුම්දීම යවනු ලැබේ',
  'Option One': 'පළමු විකල්පය',
  'Option Two': 'දෙවන විකල්පය',
  'Option Three': 'තෙවන විකල්පය',
  'Option Four': 'සිව්වන විකල්පය',
  'Option Five': 'පස්වන විකල්පය',
  'Item 1': 'අයිතමය 1',
  'Item 2': 'අයිතමය 2',
  'Item 3': 'අයිතමය 3',
  'All statuses': 'සියලු තත්ත්ව',
  'Recent searches': 'මෑත සෙවීම්',
};

const Map<String, String> _ta = {
  'Continue': 'தொடரவும்',
  'Cancel': 'ரத்துசெய்',
  'Add': 'சேர்',
  'Download': 'பதிவிறக்கு',
  'Add Document': 'ஆவணத்தைச் சேர்',
  'Show dialog': 'உரையாடலைக் காட்டு',
  'Show bottom sheet': 'கீழ்த் தாளைக் காட்டு',
  'Show snack bar': 'அறிவிப்பைக் காட்டு',
  'Open menu': 'பட்டியலைத் திற',
  'Apply for a fuel quota pass':
      'எரிபொருள் ஒதுக்கீட்டு அனுமதிக்கு விண்ணப்பிக்கவும்',
  'Label': 'சிட்டை',
  'Title': 'தலைப்பு',
  'Help Text': 'உதவி உரை',
  'Help text': 'உதவி உரை',
  'Helper text': 'உதவி உரை',
  'Hint': 'குறிப்பு',
  'Hint Text': 'குறிப்பு உரை',
  'Error Text': 'பிழை உரை',
  'Error text': 'பிழை உரை',
  'Description': 'விவரம்',
  'Description placeholder': 'விவர இடம்',
  'Enter the description text': 'விவர உரையை உள்ளிடவும்',
  'Page Title': 'பக்கத் தலைப்பு',
  'Page content': 'பக்க உள்ளடக்கம்',
  'Card content': 'அட்டை உள்ளடக்கம்',
  'Sheet content goes here': 'தாள் உள்ளடக்கம் இங்கு வரும்',
  'Content': 'உள்ளடக்கம்',
  'Value': 'மதிப்பு',
  'Message': 'செய்தி',
  'Title Text': 'தலைப்பு உரை',
  'Tooltip Title': 'கருவிக்குறிப்புத் தலைப்பு',
  'About this field': 'இந்தப் புலம் பற்றி',
  'Dialog Title': 'உரையாடல் தலைப்பு',
  'Basic dialog title': 'அடிப்படை உரையாடல் தலைப்பு',
  'Accordion Name': 'அக்கார்டியன் பெயர்',
  'Collapsed by default.': 'இயல்பாக மடக்கப்பட்டுள்ளது.',
  'Service Name': 'சேவைப் பெயர்',
  'Divider': 'பிரிப்பான்',
  'Progress': 'முன்னேற்றம்',
  'Step label': 'படி சிட்டை',
  'Legend': 'விளக்கம்',
  'Subtitle': 'துணைத் தலைப்பு',
  'Badge': 'சின்னம்',
  'NEW': 'புதிது',
  'Accepted': 'ஏற்கப்பட்டது',
  'Success': 'வெற்றி',
  'Error': 'பிழை',
  'Loading': 'ஏற்றுகிறது',
  'Modal': 'முறைமை',
  'Icon': 'சின்னம்',
  'Trailing': 'பின்தொடர்',
  'Input': 'உள்ளீடு',
  'Prefix': 'முன்னொட்டு',
  'Suffix': 'பின்னொட்டு',
  'Time': 'நேரம்',
  'National Identity Card': 'தேசிய அடையாள அட்டை',
  'Birth Certificate': 'பிறப்புச் சான்றிதழ்',
  'Driving License': 'ஓட்டுநர் உரிமம்',
  'Fuel Pass': 'எரிபொருள் அனுமதி',
  'My Account': 'எனது கணக்கு',
  'Mobile Number': 'கைபேசி எண்',
  'Email': 'மின்னஞ்சல்',
  'NIC number': 'தே.அ.அ. எண்',
  'Licence number': 'உரிம எண்',
  'Application ID': 'விண்ணப்ப அடையாளம்',
  'Submitted date': 'சமர்ப்பித்த தேதி',
  'Current status': 'தற்போதைய நிலை',
  'District': 'மாவட்டம்',
  'Select district': 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
  'Shipping address': 'அனுப்பும் முகவரி',
  'Street address': 'தெரு முகவரி',
  'City': 'நகரம்',
  'Postal code': 'அஞ்சல் குறியீடு',
  'Date posted': 'அனுப்பிய தேதி',
  'Where should we deliver your order?': 'உங்கள் ஆர்டரை எங்கு வழங்க வேண்டும்?',
  'All fields in this group are required.':
      'இந்தக் குழுவின் அனைத்துப் புலங்களும் தேவை.',
  'Please complete every field before continuing.':
      'தொடர்வதற்கு முன் அனைத்துப் புலங்களையும் நிரப்பவும்.',
  'Enter your NIC Number correctly': 'உங்கள் தே.அ.அ. எண்ணைச் சரியாக உள்ளிடவும்',
  'Enter you Birth date correctly': 'உங்கள் பிறந்த தேதியைச் சரியாக உள்ளிடவும்',
  'Enter a valid number': 'சரியான எண்ணை உள்ளிடவும்',
  'File size is too big': 'கோப்பு அளவு மிகப் பெரியது',
  'Your Birth Certificate is ready': 'உங்கள் பிறப்புச் சான்றிதழ் தயார்',
  'Download it now or collect it from your selected office.':
      'இப்போது பதிவிறக்கவும் அல்லது நீங்கள் தேர்ந்தெடுத்த அலுவலகத்தில் பெறவும்.',
  'No documents added yet': 'இதுவரை ஆவணங்கள் சேர்க்கப்படவில்லை',
  'Your uploaded documents will appear here once added.':
      'நீங்கள் பதிவேற்றும் ஆவணங்கள் சேர்க்கப்பட்டதும் இங்கு தோன்றும்.',
  'System is down for Maintenance': 'பராமரிப்புக்காக அமைப்பு செயலிழந்துள்ளது',
  'We promise, we\'ll be right back!':
      'உறுதியளிக்கிறோம், விரைவில் திரும்பி வருவோம்!',
  'Pull down from the top to refresh': 'புதுப்பிக்க மேலிருந்து கீழே இழுக்கவும்',
  'Swipe to dismiss': 'நிராகரிக்க ஸ்வைப் செய்யவும்',
  'Prepare documents': 'ஆவணங்களைத் தயாரிக்கவும்',
  'Gather all required identification and supporting files':
      'தேவையான அனைத்து அடையாள மற்றும் துணைக் கோப்புகளையும் சேகரிக்கவும்',
  'Submit application': 'விண்ணப்பத்தைச் சமர்ப்பிக்கவும்',
  'Upload documents through the online portal':
      'இணையவழி வாயில் மூலம் ஆவணங்களைப் பதிவேற்றவும்',
  'Verification in progress': 'சரிபார்ப்பு நடைபெறுகிறது',
  'Our team reviews your documents (2–5 business days)':
      'எங்கள் குழு உங்கள் ஆவணங்களை மதிப்பாய்வு செய்கிறது (2–5 வேலை நாட்கள்)',
  'Receive approval': 'ஒப்புதலைப் பெறவும்',
  'Notification sent via email and SMS':
      'மின்னஞ்சல் மற்றும் குறுஞ்செய்தி வழியாக அறிவிப்பு அனுப்பப்படும்',
  'Option One': 'முதல் விருப்பம்',
  'Option Two': 'இரண்டாம் விருப்பம்',
  'Option Three': 'மூன்றாம் விருப்பம்',
  'Option Four': 'நான்காம் விருப்பம்',
  'Option Five': 'ஐந்தாம் விருப்பம்',
  'Item 1': 'உருப்படி 1',
  'Item 2': 'உருப்படி 2',
  'Item 3': 'உருப்படி 3',
  'All statuses': 'அனைத்து நிலைகளும்',
  'Recent searches': 'சமீபத்திய தேடல்கள்',
};
